services:
  kafka-1:
    image: registry.hub.docker.com/apache/kafka:4.1.1
    container_name: kafka-1
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "9092:9092"
    volumes:
      - ./data-kafka-1:/var/lib/kafka/data
    networks:
      - core_podman_network
    restart: unless-stopped

# volumes:
#   kafka-data:

networks:
    core_podman_network:
      external: true
